const data = {
  products: [
    {
      name: 'Nike slim shirt',
      slug: 'nike-slim-shirt',
      image: '/images/p1.jpg',
      category: 'Shirts',
      price: 1200,
      countInStock: 10,
      brand: 'Nike',
      rating: 4,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas slim shirt',
      slug: 'adidas-slim-shirt',
      image: '/images/p2.jpg',
      category: 'Shirts',
      price: 1210,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike slim pants',
      slug: 'nike-slim-pants',
      image: '/images/p3.jpg',
      category: 'Shirts',
      price: 1330,
      countInStock: 10,
      brand: 'Nike',
      rating: 4,
      numReviews: 10,
      description: 'high quality pant',
    },
    {
      name: 'Nike slim pants',
      slug: 'nike-slim-pants',
      image: '/images/p3.jpg',
      category: 'Shirts',
      price: 1330,
      countInStock: 10,
      brand: 'Nike',
      rating: 4,
      numReviews: 10,
      description: 'high quality pant',
    },
  ],
};
export default data;
